# Generated by Django 4.0.5 on 2022-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.FileField(null=True, upload_to='covers'),
        ),
    ]
